name: Terraform Apply
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
  # Configure job to download source bundle artifact from previous workflow
  UploadSourceBundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # only include application.go, go.mod and go.sum are needed for the source bundle
      - name: Create source bundle
        run: zip -r source-bundle.zip application.go go.mod go.sum
      
      - name: Upload source bundle artifact
        uses: actions/upload-artifact@v5
        with:
          name: eb-source-bundle
          path: source-bundle.zip
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Download EB source bundle artifact
        uses: actions/download-artifact@v5
        id: download-source-bundle
        with:
          name: eb-source-bundle
          path: .
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume:  ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: terraform-aws-oidc-example
          aws-region: us-east-1
      
      - uses: hashicorp/setup-terraform@v3

      - name: initialize terraform 
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
        # Add path to terraform files if they are not in the repository root
        working-directory: ./terraform
      
      - name: validate terraform configuration files
        run: terraform validate
        # Add path to terraform files if they are not in the repository root
        working-directory: ./terraform

      - name: run terraform apply to update aws infrastructure
        run: terraform apply --auto-approve
        # Add path to terraform files if they are not in the repository root
        working-directory: ./terraform